(print-graph '(3 2 5 6 7 5 3 4 6 4 3 2 1) 2)

(let* ((dir "c:/Program Files/Emacs/emacs-29.4/share/emacs/29.4/lisp/mail/")
       (list-of-files (files-in-below-directory dir))
       (lengths (lengths-list-many-files list-of-files))
       (sorted-lengths (sort lengths '<))
       (horizontal-step 10)
       (top-of-ranges (number-sequence 10 300 horizontal-step))
       (full-range (defuns-per-range sorted-lengths top-of-ranges))
       (vertical-step 10)
       (numbers-list (mapcar (lambda (arg) (/ arg vertical-step)) full-range))
       (graph-symbol "**")
       (graph-blank "  ")
       (X-axis-tic-symbol "||"))
  (insert (format "%s" numbers-list) "\n\n")
  (print-graph numbers-list vertical-step horizontal-step))
