(require 'ert)
(require 'stack)
(require 'test-utils)

(ert-deftest stack-test ()
  (let ((s (make-stack)))
    (should (null (stack-push s 1)))
    (should (equal (stack-pop s) 1))

    (stack-push s 2)
    (stack-push s 3)
    (stack-push s 4)
    (should (equal (stack-pop s) 4))
    (should (equal (stack-peek s) 3))
    (should (equal (stack-size s) 2))

    (stack-pop s)
    (stack-pop s)
    (should (null (stack-peek s)))
    (should (zerop (stack-size s)))
    (assert-error (stack-pop s) "No such element")))

(ert-deftest array-stack-test ()
  (let ((s (make-array-stack 3)))
    (should (null (array-stack-push s 1)))
    (should (equal (array-stack-pop s) 1))

    (array-stack-push s 2)
    (array-stack-push s 3)
    (array-stack-push s 4)
    (assert-error (array-stack-push s 5) "Stack is full")
    (should (equal (array-stack-pop s) 4))
    (should (equal (array-stack-peek s) 3))
    (should (equal (array-stack-size s) 2))

    (array-stack-pop s)
    (array-stack-pop s)
    (should (null (array-stack-peek s)))
    (should (zerop (array-stack-size s)))
    (assert-error (array-stack-pop s) "No such element")))
